In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
X = torch.arange(4)
torch.save(X, 'X-file')

In [3]:
X2 = torch.load('X-file')
X2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([X, y], 'X-file')

In [5]:
X2, y2 = torch.load('X-file')
(X2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [6]:
mydict = {'X': X, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'X': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [8]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

In [10]:
net = MLP()
X = torch.randn(size=(2, 20))
y = net(X)

In [11]:
torch.save(net.state_dict(), 'mlp-params')

In [12]:
clone = MLP()
clone.load_state_dict(torch.load('mlp-params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
y_clone = clone(X)
y_clone == y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])