张量（tensor）：
n维数组，类似numpy的ndarray
numpy只支持CPU计算，tensor支持GPU加速计算

0-d 标量
[.]

1-d 向量
[. . .] 一个特征向量

2-d 矩阵
[[...]
 [...]]
一个样本的特征举证

3-d
[[[...
  ...]]]
RGB图片（宽×高×通道）
ps：宽-列、高-行、通道-R、G、B

4-d
[[[[...]]]]
一批RGB图片（批量大小×宽×高×通道）

5-d
[[[[...]]]
一个视频批量（批量大小×时间×宽×高×通道）

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape # 张量的形状

torch.Size([12])

In [4]:
x.numel() # 张量中元素的总数

12

In [5]:
X = x.reshape(3, 4) # 改变张量的形状，不改变元素数量和值；行 × 列 = 元素个数
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
X = x.reshape(-1, 4) # 指定列数，行数自动计算，但是 元素个数 / 指定列数 = 整数
X = x.reshape(3, -1) # 同上
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

特定常量、特定分布中随机采样的数字初始化矩阵

In [7]:
torch.zeros((2, 3, 4)) # 内层括号有没有都可以

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn((3, 4)) # 元素从均值为0、标准差为1的标准高斯分布（正态分布）随机采样

tensor([[-0.4068,  2.4011, -0.7301, -0.4125],
        [ 0.8217, -0.3405, -0.5353, -0.6702],
        [-0.3486, -0.0963,  0.1775,  0.3199]])

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [3, 2, 1, 4]]) # 从指定的python列表（嵌套）给元素赋值；外层是轴0，内层是轴1

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [3, 2, 1, 4]])

张量运算：两个张量必须相同形状，按元素计算
+ - * / **

In [11]:
x = torch.tensor([1.0, 2, 4, 8]) # 1.0表示创建浮点运算
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量连接：指定两个张量按照沿着哪个轴（dim）连接

In [13]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [3, 2, 1, 4]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)
# dim：维度
# dim = 0 表示第0维，可以理解为行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  2.,  1.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  2.,  1.,  4.]]))

逻辑运算符构建张量 >、<、==

In [14]:
x == y # 判断两个二元张量每个元素是否相等

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
x.sum() # 所有元素求和

tensor(66.)

广播机制
（1）通过适当复制元素扩展一个或两个数组，转换后两个张量具有相同的形状
（2）对生成的数组执行按元素操作
大多数沿着数组中长度为1的轴进行广播

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

张量的索引和切片访问
第一个元素索引是0，最后一个元素索引是-1

In [17]:
x[-1], x[1:3] # 前闭后开

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

内存节省：切片操作将计算结果分配给之前的地址，减少内存开销

In [19]:
before = id(y)
y = y + x
id(y) == before # 执行 y = y + x后，python为y分配新的内存

False

In [20]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2211136808816
id(z): 2211136808816


In [21]:
before = id(x)
x += y # 可以替换切片操作
before == id(x)

True

对象转换：张量和numpy转换，二者共用底层内存

In [22]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
# 大小为1的张量转换为python标量
a = torch.tensor([4.8])
a, a.item(), float(a), int(a) #item()和float()的结果不精确

(tensor([4.8000]), 4.800000190734863, 4.800000190734863, 4)