标量

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x - y, x * y, x / y, x ** y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

向量：标量值组成的列表，标量值称为向量的元素；一个轴的张量

通过下标访问向量的任意元素，其中列向量是向量的默认方向

长度（维度）：向量或轴维度表示向量或轴的元素数量

ps：张量的维度表示张量具有的轴数，张量某个轴的维度是该轴的长度

函数：len() 或 .shape 

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[2]

tensor(2)

In [4]:
len(x), x.shape

(4, torch.Size([4]))

矩阵：具有两个轴的向量

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.$$
:eqlabel:`eq_matrix_def`

特征向量：Ax = $\lambda$x（不被矩阵改变方向的向量）

其中x的特征向量，$\lambda$是特征值

ps：对称矩阵总是有特征向量

单位矩阵：对角线全为1，其余全为0

对角矩阵：对角线不为0，其余为0

逆矩阵：A、B两个矩阵满足AB = BA = E（单位矩阵）

对称矩阵：n阶矩阵（方阵）满足$a_{ij} = a_{ji},$  $A = A^T$

正定矩阵：$x^TAx$ $\geq 0$，A是正定矩阵

正交矩阵：满足逆矩阵 = 转置矩阵的矩阵，其所有的行/列向量之间相互正交（向量垂直，点积为0），且所有的列向量是单位向量

置换矩阵：方阵的每一行、每一列具只有一个1，其余全为0，用来和方阵相乘做交换

范数：矩阵长度

c = A·b bence ||c|| $\geq$ ||A||·||b||

矩阵范数：满足上式最小的值

Frobenius范数：矩阵所有的值平方求和再开方

In [5]:
# 矩阵
A = torch.arange(9).reshape(3, 3)
A, A.T # 矩阵和其转置
A == A.T # 判断两个矩阵是否相等

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [6]:
# 张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 分配新的内存clone A的副本
A, A + B
print('id(A)：', id(A))
print('id(B)：', id(B))

id(A)： 2742066868112
id(B)： 2742067010032


In [7]:
# 哈达玛积：按元素乘法
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [8]:
a = 2
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 torch.Size([2, 3, 4]))

In [13]:
# 降维
# 降维求和
x = torch.arange(48, dtype=torch.float32).reshape(2, 3, 8)
x, x.shape, x.sum() # sum()默认全部降维

(tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.]],
 
         [[24., 25., 26., 27., 28., 29., 30., 31.],
          [32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47.]]]),
 torch.Size([2, 3, 8]),
 tensor(1128.))

In [14]:
x.sum(axis=0) # 指定轴降维

tensor([[24., 26., 28., 30., 32., 34., 36., 38.],
        [40., 42., 44., 46., 48., 50., 52., 54.],
        [56., 58., 60., 62., 64., 66., 68., 70.]])

In [15]:
x.sum(axis=[0, 1]) # 指定两个维度降维

tensor([120., 126., 132., 138., 144., 150., 156., 162.])

In [16]:
x.mean(), x.sum() / x.numel() # 等价求平均值 all元素

(tensor(23.5000), tensor(23.5000))

In [17]:
x.mean(axis=1), x.sum(axis=1) / x.shape[1] # 指定维度求平均值，分子用x.shape[?]

(tensor([[ 8.,  9., 10., 11., 12., 13., 14., 15.],
         [32., 33., 34., 35., 36., 37., 38., 39.]]),
 tensor([[ 8.,  9., 10., 11., 12., 13., 14., 15.],
         [32., 33., 34., 35., 36., 37., 38., 39.]]))

In [19]:
# 非降维求和
sum_x = x.sum(axis=1, keepdims=True)
sum_x.shape

torch.Size([2, 1, 8])

In [20]:
# 广播
x / sum_x

tensor([[[0.0000, 0.0370, 0.0667, 0.0909, 0.1111, 0.1282, 0.1429, 0.1556],
         [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6296, 0.6000, 0.5758, 0.5556, 0.5385, 0.5238, 0.5111]],

        [[0.2500, 0.2525, 0.2549, 0.2571, 0.2593, 0.2613, 0.2632, 0.2650],
         [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4141, 0.4118, 0.4095, 0.4074, 0.4054, 0.4035, 0.4017]]])

In [30]:
# 指定沿某个轴求累加和
x, x.cumsum(axis = 0)

(tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.]],
 
         [[24., 25., 26., 27., 28., 29., 30., 31.],
          [32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47.]]]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.]],
 
         [[24., 26., 28., 30., 32., 34., 36., 38.],
          [40., 42., 44., 46., 48., 50., 52., 54.],
          [56., 58., 60., 62., 64., 66., 68., 70.]]]))

In [35]:
# 向量点积
y = torch.arange(8, dtype=torch.float32)
x = torch.ones_like(y)
x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]),
 tensor(28.),
 tensor(28.))

In [37]:
# 矩阵向量积
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
x = torch.arange(5, dtype=torch.float32) # 默认是列向量
torch.mv(A, x)

tensor([ 30.,  80., 130., 180.])

In [41]:
# 矩阵矩阵积
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
B = torch.arange(30, dtype=torch.float32).reshape(5, 6)
torch.mm(A, B)

tensor([[ 180.,  190.,  200.,  210.,  220.,  230.],
        [ 480.,  515.,  550.,  585.,  620.,  655.],
        [ 780.,  840.,  900.,  960., 1020., 1080.],
        [1080., 1165., 1250., 1335., 1420., 1505.]])

In [43]:
# 范数
# torch.norm() 默认L2范数 平方和范数   对于矩阵是F范数
u = torch.tensor([-3.0, 4.0])
torch.norm(u)

tensor(5.)

In [44]:
# torch.abs(x).sum() L1范数 绝对值和范数
torch.abs(u).sum()

tensor(7.)

In [46]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [47]:
# 练习
# 1.
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
A == A.T.T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [49]:
# 2.
B = A.clone()
A.T + B.T == (A + B).T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [51]:
# 3. pass
# 4. pass
# 5. pass
# 6.
A / A.sum(axis=1) # 报错 shape不一致，需要keepdims=True

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

In [ ]:
# 7. pass