In [1]:
import torch

# 隐式构造
x = torch.arange(4.0)
x.requires_grad_(True)  # 等价于 x = torch.arange(4.0, requires_grad=True)
print(x.grad)

None


In [2]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [3]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [4]:
x.grad == 4 * x

tensor([True, True, True, True])

In [5]:
x.grad.zero_() # pytorch会累计梯度，因此需要清除之前的值
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [6]:
# 向量的反向传播
x.grad.zero_()
y = x * x
y = x.sum().backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
def f(a):
    b = a * 2
    while b.norm() < 1000:  # L2范数
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [8]:
a = torch.randn(size=(), requires_grad=True) # 生成一个标量，满足标准正态分布
d = f(a)
d.backward()

In [9]:
a.grad == d / a

tensor(False)

In [10]:
# 3.
t1 = torch.arange(3.0, requires_grad=True)
t2 = torch.tensor([2.0,3.0,4.0], requires_grad=True)
t = t1 * t2
t.backward(gradient=torch.ones_like(t1)) # 需要加一个gradient 本质是计算的结果乘上gradient
t1.grad

tensor([2., 3., 4.])

In [22]:
# 4.
def f(a):
    b = a * 2
    while b.norm() < 10:
        b = b + b * 3
    if b > 0:
        c = b
    else:
        c = b * 2
    return c

x = torch.tensor([2.0], requires_grad=True)
y = f(x)
y.backward()
x.grad

tensor([8.])